Optimistic async state hashing
marigold-dev/deku pull request #234
Opened 2021-10-13 21:57 UTC by d4hines

## Depends

- [ ] #232

## Problem

We want async state hashing per #147. 

This review is highly contingent on #232 - please review that one first. 

## Solution

#232 lifts state hashing from inside `Protocol` to inside the node. 

This PR is an incremental step towards full async hashing. In the best case, hashing is done fully asynchronously; however, if the hash is not finished, the node hashes the state synchronously on demand. 

To achieve this, the PR builds on #232 in two steps (1 commit per step):

1. First, it drops the notion of `next_state_root_hash`. Instead, we extend the node state with two fields:
  - `current_epoch` - an integer identifier for the current state root hash epoch.
   - `finished_hashes` - a map from epochs to the corresponding hash.
   - In the "setter" function, we build in a filter that drops any hashes older than the current epoch. This prevents the map from growing forever and also prevents the epoch from moving backwards.
  - This commit should not change the behavior in any way from #232 - reviewers, please help me check this!
2.  Next, we add an additional way to add hashes to the map, namely via async state hashing. We also slightly modify the `apply_block` function to be optimistic: if the map already contains the hash (because of async state hashing), then we use that value - otherwise,  we generate the hash synchronously. This allows us to have aysnc state hashing while never getting out of sync because of slow hashing. The cost of course is that some hashes may be done twice. 

In the next PR, we'll add more sophistication on the case where the hash is not already finished, adding a notion of in-sync and out-of-sync. 

## Related

- #147

2021-10-20 00:03 UTC, EduardoRFS requested changes

2021-10-20 00:03 UTC, EduardoRFS commented on node/state.re
> +let increment_epoch = state => {
Better name would be `start_new_epoch`

2021-11-17 22:49 UTC, d4hines commented
This had a bug similar to the one I addressed in #227 but I've rebased and fixed.

2022-01-12 18:35 UTC, d4hines commented
This PR has been rebased and tested.

2022-01-12 20:16 UTC, d4hines commented
Some further testing leads me to believe that although this branch works, it's not working as intended. I think it's hitting the fallback case and synchronously hashing every time.

2022-01-27 13:46 UTC, d4hines commented
Superseded by #412

2022-01-27 13:46 UTC, closed without merging