D4hines/setup scripts
marigold-dev/deku pull request #288
Opened 2021-11-10 15:22 UTC by d4hines

## Depends
- [ ] #287

## Problem

There are several problems with running on public infrastructure for the "inner loop" of local development:
- It's quite complicated to set up. You have to 
  - Run a Tezos node, which itself has many substeps, addressed in @fraidev 's [instructions](https://hackmd.io/Er_EPZIrQSardvo4bpuYJg?view)
  - Set up a new wallet
  - Get funds for that wallet using the faucet or our new faucet-bot
  - Configure validator identities
  - Compile the ligo contract, instantiate it with those identities, and deploy the contract
  - Only now can you start the cluster using `start.sh` or tmuxinator
- All of this is quite slow, since bootstrapping the node and deploying the contract take a long time on testnets.
- This workflow depends on public infrastructure being online (and of course requires an internet connection to work, etc.)

## Solution

Fortunately, the [Flextesa](https://tezos.gitlab.io/flextesa/) project provides an easy way to run your own local Tezos network in a sandbox, to which you can deploy the consensus contract.

I've created a script `sandbox.sh` that extends the original `setup.sh` to do the following:
- setup a flextesa sandbox network using Docker
- create the validator identities/config
- compile and deploy the consensus contract to the sandbox

# Related

NA

2021-11-10 19:43 UTC, d4hines commented
Comment for reviewers: The history looks messy but it's not bad. First several commits are the dependencies. Then I tried to clean up the script in stages so the changes stay clear (first renaming, then fixing the formatting, then the change).

2021-11-16 14:13 UTC, anchpop approved these changes

2021-11-16 20:18 UTC, Zett98 approved these changes

2021-11-17 00:09 UTC, rosalogia approved these changes

2021-11-18 14:43 UTC, EduardoRFS requested changes
Just couple changes, in general I don't like this patch but the alternatives are worse.

2021-11-18 14:43 UTC, EduardoRFS commented on sandbox.sh
> +create_new_validators() {
This is not only creating new validators, it setup's the entire deku environment

2021-11-18 14:43 UTC, EduardoRFS commented on sandbox.sh
> +start)
I would say rename the commands to `setup` and `prune`. As they're not safe commands, while `start` and `stop` should never destroys data.

2021-11-19 10:40 UTC, EduardoRFS approved these changes
![dragon maid approving this PR](https://user-images.githubusercontent.com/3393115/142608642-6e638534-59ec-4597-b217-b1b7dea48edc.gif)

2021-11-19 10:41 UTC, merged