Add deku-cli and deku-node as apps in nix
marigold-dev/deku pull request #524
Opened 2022-04-01 13:11 UTC by ulrikstrid

## Problem

Now that we have flakes it would be nice to have a simple way of running our tools with it

## Solution

Adding the `deku-cli` and `deku-node` as apps.
They can now be run from the repository like `nix run .#deku-cli` or `nix run .#deku-node`.
We should also be able to run `nix run github:marigold-dev/deku#deku-cli` from anywhere.

2022-04-01 18:42 UTC, d4hines requested changes
What's going on with the formatting? I'd appreciate if we could separate formatting into separate commits. 

Besides that, change looks good.

2022-04-04 07:39 UTC, gsebil08 reviewed
Does it worth it to add some documentation?

2022-04-04 16:42 UTC, d4hines requested changes
There's a typo in flake.nix

2022-04-04 16:42 UTC, d4hines commented on flake.nix
> +        app = {
```suggestion
        apps = {
```

2022-04-04 23:24 UTC, d4hines approved these changes
LGTM

2022-04-05 07:35 UTC, gsebil08 commented
> > Does it worth it to add some documentation?
> 
> @gsebil08, personally I don't think so: EDIT: I had the command wrong the first time. Fixed.
> 
> ```
> nix run .#deku-cli -- --help
> nix run .#deku-node -- --help
> ```
> 
> will print out quite a bit of documentation.
> 
> What kind of docs are you looking for?

Basic simple user documentation, like in our `readme.md` add something like:
> ## Run a node with nix
> Simply run the following commands to run a deku-node:
>```shell script
> $ nix run .#deku -- data/0
> ```

2022-04-05 13:35 UTC, merged