Lambda vm IO primitives
marigold-dev/deku pull request #544
Opened 2022-04-13 17:45 UTC by renatoalencar

## Depends

- [ ] #508 

## Problem

Lambda VM needs a way to access external information that are not the parameters of the smart contract, such as the operation sender or contract address.

## Solution

Introduce IO primitives for Lambda VM, currently only for sender address.

I also moved gas as well as sender address to a single record named `context`. `sender` should be of `value Lazy.t`, because it needs to be encoded as Lambda VM value, and so it requires to be compiled, which requires gas. So in order to avoid increasing gas cost for contracts that do not use the sender address, this is lazy so it's only compiled after actually been required.

2022-04-21 19:08 UTC, Zett98 requested changes

2022-04-21 19:08 UTC, Zett98 commented on src/lambda_vm/interpreter.mli
> +type context = {
please move it to a separate module and create a ```make``` function for building the context and functions to interact with it through abstract module

2022-04-21 19:40 UTC, renatoalencar commented on src/lambda_vm/ast.ml
> +type io_prim = Sender
sorry, that one passed unnoticed  when I was rebasing stuff from main.

2022-04-22 20:39 UTC, Zett98 approved these changes

2022-04-22 20:39 UTC, merged