add tutorial to deposit and withdraw tickets
marigold-dev/deku pull request #598
Opened 2022-05-11 12:41 UTC by Pilou97

## Problem

There is no documentation or guide to deposit or withdraw tickets on deku

## Solution
Creates a tutorial section to do it

2022-05-12 01:29 UTC, d4hines requested changes
First, thanks for writing this up @Pilou97!

However, I would prefer if we added a command to the ./sandbox.sh script and tested it in the CI e2e testing. It much more important to me that we have automation and CI to keep things green than docs right now.

Can you convert this into a command and add the CI?

2022-05-12 10:40 UTC, gsebil08 reviewed
Only format comments, thanks for this doc 😍

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +- withdraw as alice
```suggestion
1. start deku
2. originate a ticket contract
3. deposit ticket on deku
4. transfer to alice
5. withdraw as alice
```

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +## Deploy a contract that holds tickets
```suggestion
## Deploy a contract holding tickets
```

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +Creates a contract which can deposit or withraw tickets from the conscensus contract
```suggestion
Creates a contract which can deposit or withdraw tickets from the consensus contract
```

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +```
Add `bash`

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +> New contract KT1WyREzcYATwbcbGPnLvDvUAHQcY7SJLm82 originated.
```suggestion
> [...]
> New contract KT1WyREzcYATwbcbGPnLvDvUAHQcY7SJLm82 originated.
> [...]
```

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +### Possible error (solved by retrying):
```suggestion
### Possible error (solved by retrying)
```

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +Creates `n` tickets (10000000 defined in the contract) and deposit them in the conscensus contract so that there are available in deku for the address `tz1RPNjHPWuM8ryS5LDttkHdM321t85dSqaf` (deku add
```suggestion
Creates `n` tickets (10000000 defined in the contract) and deposit them in the consensus contract so they are available in deku for the address `tz1RPNjHPWuM8ryS5LDttkHdM321t85dSqaf` (deku address hard coded in the `sandbox.sh` script)
```

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +Alice need an address on deku
```suggestion
Alice needs an address on deku
```

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +deku-cli create-wallet
I guess we should add an output example. This will make the following sentence (`and save the field address`) easier to understand.

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +Creates a wallet for the ticket holder named wallet.json:
```suggestion
Create a wallet for the ticket holder named wallet.json:
```

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +Transfer 10 tickets from `wallet.json` to alice
`Alice` instead of `alice` everywhere

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +```
Add ` bash`

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +### Possible error:
```suggestion
### Possible error
```

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +Alice must have tez in its tezos account to pay the fees of the withdraw
```suggestion
Alice must have ꜩ in her Tezos account to pay the fees of the withdrawal.
```

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +where the arg is the output of the withdraw-proof command.
```suggestion
where `-arg` is the output of the `deku-cli withdraw-proof` command.
```

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +```
add bash

2022-05-12 10:40 UTC, gsebil08 commented on tutorials/deposit-withdraw.md
> +```
add bash

2022-05-25 12:48 UTC, gsebil08 commented
@d4hines I am not fond of making it a script. The goal of this markdown is to make everyone able to use the different commands.
Just making it in a script, would totally mask the complexity, like with sandbox.sh.

But I totally agreed on the second point:
>It much more important to me that we have automation and CI to keep things green than docs right now

The documentation is the V0 of a great e2e testing in CI. And this scenario must definitively be in our CI.

2022-06-10 10:17 UTC, lykimq commented
Can you rebase with main and put the folder `tutorial` in `docs`? 
The ticket `dummy_ticket.mligo` you can remove it as it already in main.

2022-06-10 10:17 UTC, lykimq approved these changes

2022-06-15 09:40 UTC, aguillon commented
Regarding this PR: I'm now convinced that it provides value to newcomers, so we have a choice between merging it to the docs with the risk that it helps nobody (because we forget about maintaining it, because they miss it, stuff like that) or putting it in HackMD instead, where we're almost certain that nobody is going to read it (best case scenario is, we have one or two team members that join before the doc definitely becomes obsolete).

I prefer the first option, but I'm open to counter-arguments. I'll decide and merge it or close it on Friday.

2022-06-29 15:21 UTC, aguillon commented
So, actually:
* users will have a better, higher-level manual;
* we should have a better knowledge sharing tool, but this repository is not it.

2022-06-29 15:21 UTC, closed without merging