State hash benchmarking
marigold-dev/deku pull request #688
Opened 2022-06-10 18:07 UTC by InfiniteSwerve

## Problem
Right now our state hashing uses yojson, and we didn't have a benchmark to see how fast this was, or compare it to other options.

## Solution
This PR builds a pseudo state and compares the hashing time of using yojson and bin_prot

2022-06-10 18:12 UTC, lykimq approved these changes
LGTM.

2022-06-10 20:11 UTC, rosalogia commented on benchmarks/state_hash/README.md
> +```
Maybe I'm missing some important details, what is percentage here?

2022-06-10 20:25 UTC, rosalogia commented on benchmarks/state_hash/maps.ml
> +module Encoding = struct
:smile: my code is going places.

2022-06-10 20:26 UTC, rosalogia approved these changes
Code makes sense, glad we have some benchmarking on these things in particular since I was rather curious. Nicely done.

2022-06-10 20:42 UTC, d4hines requested changes

2022-06-16 01:47 UTC, d4hines requested changes
The code doesn't build. I get this error:
```
File "benchmarks/state_hash/bench_state_hash.ml", line 32, characters 18-66:
32 |         make_test Map_hash.Hash_the_map_yojson.hash_the_map_yojson params
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Map_hash.Hash_the_map_yojson
```

2022-06-16 01:50 UTC, d4hines commented
https://github.com/marigold-dev/deku/pull/695 to make sure don't miss broken builds in the future.

2022-06-21 09:21 UTC, lykimq approved these changes

2022-06-21 09:34 UTC, lykimq commented
> The code doesn't build. I get this error:
> 
> ```
> File "benchmarks/state_hash/bench_state_hash.ml", line 32, characters 18-66:
> 32 |         make_test Map_hash.Hash_the_map_yojson.hash_the_map_yojson params
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Error: Unbound module Map_hash.Hash_the_map_yojson
> ```

I think it fixes now, and I also tested with `dune build @check`.

2022-06-22 16:03 UTC, aguillon requested changes
Thank you for this PR. I don't have much experience with benchmarking and, in particular, I have never used the Core_bench library, so I asked a few questions.

The main problem I have here is that this benchmark could give us some information about what is gained by switching from one serialization format to the other, but there's probably too much noise in the result for several reasons. On one hand, it does not matter much as this is just a benchmark, which clearly gives Bin_prot the upper hand; on the other hand, this is a very unsurprising result, and thus I hope we could learn more by having a more precise, efficient and fair methodology, which could give us some performance ratio (meh, data).

Btw, what's the percentage column about? Do we have standard deviations somewhere?

2022-06-22 19:18 UTC, EduardoRFS commented on benchmarks/state_hash/map_hash.ml
> +    let map = generate_maps bmap_size smap_size in
Core_bench has no say when data is created, but yes it should be definitely creating the data first, otherwise you're benchmarking the GC

2022-06-23 07:39 UTC, aguillon commented on benchmarks/state_hash/map_hash.ml
> +    let map = generate_maps bmap_size smap_size in
Ok, thank you

2022-06-24 20:32 UTC, InfiniteSwerve commented
@aguillon 
> what's the percentage column about?

Percentage can be read as "percentage of the longest runtime" i.e., there are two benchmarks, A and B, where they have runtimes of 50ms and 25ms, then A's percentage would be 100, and B's would be 50.

> Do we have standard deviations somewhere?

The CLI for core_bench through dune doesn't work properly, so you can get access to confidence intervals using `Deku/_build/default/benchmarks/state_hash/bench_state_hash.exe state-hash -ci-absolute` 

You can also get access to some documentation and all the flags via
`Deku/_build/default/benchmarks/state_hash/bench_state_hash.exe help state-hash -flags`

2022-06-24 21:42 UTC, InfiniteSwerve commented on benchmarks/state_hash/bench_state_hash.ml
> +        make_test Map_hash.Bench_bin_prot.hash_map params "bin_prot :" in
This probably isn't an issue. One of the flags for core_bench will stabilize the GC between each sample run.

2022-06-24 21:42 UTC, InfiniteSwerve commented on benchmarks/state_hash/bench_state_hash.ml
> +      yojson :: bin_prot :: acc)
Good catch

2022-06-24 21:42 UTC, InfiniteSwerve commented on benchmarks/state_hash/maps.ml
> +  let bin_size_t t = to_string t |> String.bin_size_t
> you're serializing hashes by converting them to their string-hex representation

I'm not sure if that's correct. I believe @rosalogia created most of the code relating to the `Make_binable` module, so they might know?

> I'm wondering if there is a more efficient (and thus more fair regarding benchmarking) way of **doing**

There might be a more efficient way to serialize them, but this comparison was mostly about hypothesis testing. As such, I'm not sure if we'd gain much by getting more detailed numbers from the benchmark. The benchmarks makes bin_prot look like an almost 2x speedup in hashing time.

2022-06-27 14:06 UTC, aguillon approved these changes

2022-06-27 14:17 UTC, d4hines approved these changes
LGTM :+1:

2022-06-27 14:19 UTC, merged