@pilou97/remove data folder
marigold-dev/deku pull request #733
Opened 2022-06-28 09:37 UTC by Pilou97

# Problem

The `deku-cli` can only be used if you have a running Deku cluster on your machine. 

# Solution
Remove the access to the data folder of each node.

# Depends

[PR#732](https://github.com/marigold-dev/deku/pull/732)

2022-06-29 20:33 UTC, aguillon requested changes
Small changes are needed because we merged the PR removing old VMs; you can delete the `--vm_flavor` parameter.

Except for that, I guess we could improve the UX a bit, as raw exceptions (e.g. when you specify a bad deku node address with get-balance or create-transaction) are a bit harsh. We'll also definitely run into users that don't understand why create-transaction "succeeded" but get-balance shows 0.

2022-06-29 20:33 UTC, aguillon commented on src/bin/deku_cli.ml
> +        | `Dummy -> Contract_vm.Invocation_payload.dummy_of_yojson ~arg in
This is not relevant anymore.

2022-07-08 15:33 UTC, aguillon approved these changes
ty Daniel

2022-07-08 15:36 UTC, d4hines approved these changes
LGTM
![Astro boy running toward a good UX](https://media.giphy.com/media/htuleL0qoAM5SDDfZ4/giphy.gif)

2022-07-08 15:36 UTC, merged